name: autorun
on:
  schedule:
    - cron: '0 15 * * *'

jobs:
  autorun:
    runs-on: ubuntu-20.04
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: run code
        run: python3 freenom-renew/run.py -u ${{ secrets.FREENOM_USERNAME }} -p ${{ secrets.FREENOM_PASSWORD }}
