name: IBM Cloud Auto Restart

on:
 workflow_dispatch:
  push:
    branches: master
  schedule:
    - cron: 15 20 * * *

jobs:
  IBM-Cloud-CF-APP-Restart:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install CF CLI
      run: |
        curl -L "https://packages.cloudfoundry.org/stable?release=linux64-binary&source=github&version=v6" | tar -zx
        sudo mv cf /usr/local/bin
      
    - name: Login CF
      run: cf l -a https://api.us-south.cf.cloud.ibm.com login -u "realkoolisw@gmail.com" -p ${{ secrets.IBM_PWD }}
      
    - name: Restart CF APP
      run: cf rs "KooliswVM"
